"""兼容层：请使用 src.ui.input.intent。"""
from src.ui.input.intent import (
    INTENT_AGENT,
    INTENT_LINK,
    INTENT_OCR,
    INTENT_SEARCH,
    INTENT_SLASH_CACHE,
    INTENT_SLASH_METRICS,
    INTENT_SLASH_NOTE,
    INTENT_SLASH_OCR,
    INTENT_SLASH_SKILL,
    INTENT_SLASH_TASK,
    INTENT_SLASH_WEATHER,
    INTENT_WEATHER,
    InputIntent,
    classify_intent_llm,
    classify_intent_rules,
    extract_link_instruction,
    parse_slash_command,
    resolve_input_intent,
)

__all__ = [
    "INTENT_AGENT",
    "INTENT_LINK",
    "INTENT_OCR",
    "INTENT_SEARCH",
    "INTENT_SLASH_CACHE",
    "INTENT_SLASH_METRICS",
    "INTENT_SLASH_NOTE",
    "INTENT_SLASH_OCR",
    "INTENT_SLASH_SKILL",
    "INTENT_SLASH_TASK",
    "INTENT_SLASH_WEATHER",
    "INTENT_WEATHER",
    "InputIntent",
    "classify_intent_llm",
    "classify_intent_rules",
    "extract_link_instruction",
    "parse_slash_command",
    "resolve_input_intent",
]
